_prefs: 
  mapid: staceypbnj.a0e603f9
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -84.364
  - 33.786
  - 11
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 13
minzoom: 10
name: High Contrast
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,college.85de8d0b"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - martaMarkers.mss
template: ''
